"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# One settings file, two modes. Development is the default so `manage.py
# runserver` keeps working with no setup; production is opt-in:
#
#   DJANGO_ENV=prod
#   DJANGO_SECRET_KEY=<something long and random>
#   DJANGO_ALLOWED_HOSTS=api.example.com,example.com
#   DJANGO_CORS_ORIGINS=https://example.com        (browser clients)
#
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
#
# A superuser with no shell can flip the same switch from /admin/env/, which
# writes the word to ENV_FILE. The environment wins wherever it is set, so a
# deployment that exports DJANGO_ENV cannot be talked out of it through a
# browser. Either way the mode is read once, at startup: a change needs a
# restart before it means anything.
ENV_FILE = BASE_DIR / '.django_env'


def _env_mode():
    mode = os.environ.get('DJANGO_ENV')
    if mode is None:
        try:
            mode = ENV_FILE.read_text()
        except OSError:
            mode = ''
    return mode.strip().lower()


PROD = _env_mode() in ('prod', 'production')

DEBUG = not PROD


def _env_list(name):
    return [v.strip() for v in os.environ.get(name, '').split(',') if v.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-g(ro+^za612a4*7h^dvtpmwwnjy%_*@g_1c54&6f#l&9&5hf37',
)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS') if PROD else ['*']

if PROD:
    # Fail at startup rather than serve a production site with dev secrets.
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DJANGO_ENV=prod')
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be set when DJANGO_ENV=prod')

    # Assumes TLS terminates at the proxy in front of Django.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SSL_REDIRECT', '1') == '1'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CORS_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core',
]

AUTH_USER_MODEL = 'core.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.auth.ActAsOrgAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# ponytail: sqlite in both modes — one pharmacy per deployment, low write
# concurrency. Point DJANGO_DB_PATH at a volume that survives redeploys; move to
# MySQL (needs mysqlclient, not in requirements.txt yet) when concurrent writers
# start hitting "database is locked".
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH') or BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded payment receipts. Django serves these itself only while DEBUG is on
# (see config/urls.py); behind a real server, hand /media/ to it.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Wide open in development; in production only the hosts named in
# DJANGO_CORS_ORIGINS may call the API from a browser.
CORS_ALLOW_ALL_ORIGINS = not PROD
CORS_ALLOWED_ORIGINS = _env_list('DJANGO_CORS_ORIGINS') if PROD else []

# The superuser's tenant switch travels in a header, so browsers must be told
# it is allowed through.
CORS_ALLOW_HEADERS = list(default_headers) + ['x-act-as-org']
