# Generated by Django 5.2.17 on 2026-08-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_reserved',
            field=models.PositiveIntegerField(default=0, help_text='Approved but not yet dispatched. Held for those requests.'),
        ),
    ]
