# Generated by Django 5.2.17 on 2026-08-07 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_qty_reserved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set for a unit. Blank for a department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.department'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('organization', 'name'), name='uniq_department_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'parent', 'name'), name='uniq_unit_name'),
        ),
    ]
