# Generated by Django 5.2.17 on 2026-08-07 13:07

import django.db.models.deletion
from django.db import migrations, models


def units_into_their_own_table(apps, schema_editor):
    """Every department carrying a parent becomes a Unit of that parent."""
    Department = apps.get_model('core', 'Department')
    Unit = apps.get_model('core', 'Unit')
    Requisition = apps.get_model('core', 'Requisition')
    for row in Department.objects.filter(parent__isnull=False):
        unit = Unit.objects.create(
            department_id=row.parent_id, name=row.name, is_active=row.is_active,
        )
        Requisition.objects.filter(department_id=row.pk).update(department=None, unit=unit)
        row.delete()


def units_back_into_departments(apps, schema_editor):
    Department = apps.get_model('core', 'Department')
    Unit = apps.get_model('core', 'Unit')
    Requisition = apps.get_model('core', 'Requisition')
    for unit in Unit.objects.select_related('department'):
        row = Department.objects.create(
            organization_id=unit.department.organization_id,
            parent_id=unit.department_id,
            name=unit.name,
            is_active=unit.is_active,
        )
        Requisition.objects.filter(unit_id=unit.pk).update(department=row, unit=None)
        unit.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_unique_together_department_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.department'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Set instead of department when the request comes from a unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='core.unit'),
        ),
        # Before the old shape goes, or two units named alike would collide under
        # the new department-level unique_together.
        migrations.RunPython(units_into_their_own_table, units_back_into_departments),
        migrations.RemoveConstraint(
            model_name='department',
            name='uniq_department_name',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='uniq_unit_name',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'name')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('department', 'name')},
        ),
    ]
