# Generated by Django 5.2.17 on 2026-08-07 15:24

import django.db.models.functions.comparison
from django.db import migrations, models


def collapse_duplicate_drafts(apps, schema_editor):
    """Fold duplicate wishlists into one before the constraint lands.

    Nothing enforced this until now, so a database may already hold two open
    drafts for the same person, company and department. The oldest is kept and
    the rest emptied into it, quantities added where both asked for the item.
    """
    Requisition = apps.get_model('core', 'Requisition')
    RequisitionLine = apps.get_model('core', 'RequisitionLine')
    keepers = {}
    drafts = Requisition.objects.filter(
        status='DRAFT', created_by__isnull=False,
    ).order_by('id')
    for draft in drafts:
        key = (
            draft.hospital_id, draft.supplier_id, draft.created_by_id,
            draft.department_id, draft.unit_id,
        )
        keeper = keepers.setdefault(key, draft.id)
        if keeper == draft.id:
            continue
        for line in draft.lines.all():
            twin = RequisitionLine.objects.filter(
                requisition_id=keeper, product_id=line.product_id,
            ).first()
            if twin is None:
                line.requisition_id = keeper
                line.save(update_fields=['requisition'])
            else:
                twin.qty_requested += line.qty_requested
                twin.save(update_fields=['qty_requested'])
                line.delete()
        draft.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unit_remove_department_uniq_department_name_and_more'),
    ]

    operations = [
        migrations.RunPython(collapse_duplicate_drafts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='requisition',
            constraint=models.UniqueConstraint(models.F('hospital'), models.F('supplier'), models.F('created_by'), django.db.models.functions.comparison.Coalesce('department', models.Value(0)), django.db.models.functions.comparison.Coalesce('unit', models.Value(0)), condition=models.Q(('status', 'DRAFT')), name='uniq_open_draft_per_company'),
        ),
    ]
