# Generated by Django 5.2.17 on 2026-08-07 16:02

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requisition_uniq_open_draft_per_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=core.models.new_reference, max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('TRANSFER', 'Bank transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('POS', 'Card / POS')], max_length=10)),
                ('payer_reference', models.CharField(blank=True, help_text='Teller, transfer or cheque number. Required for everything but cash.', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Recorded, awaiting the supplier'), ('CONFIRMED', 'Confirmed received'), ('REJECTED', 'Not received')], default='PENDING', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_decided', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='core_paymen_invoice_cf3653_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('payer_reference', ''), _negated=True), models.Q(('status', 'REJECTED'), _negated=True)), fields=('invoice', 'payer_reference'), name='uniq_payer_reference_per_invoice')],
            },
        ),
    ]
