# Generated by Django 5.2.17 on 2026-08-07 16:20

from datetime import timedelta

import core.models
import django.core.validators
from django.db import migrations, models


def date_existing_invoices(apps, schema_editor):
    """Give invoices raised before terms existed the default 30 days."""
    Invoice = apps.get_model('core', 'Invoice')
    for invoice in Invoice.objects.filter(due_date__isnull=True).iterator():
        invoice.due_date = (invoice.issued_at + timedelta(days=invoice.terms_days)).date()
        invoice.save(update_fields=['due_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='How long a supplier gives a hospital to pay. Copied onto each invoice.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, help_text='Photo or scan of the teller slip, transfer advice or cheque.', upload_to=core.models.receipt_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'heic', 'pdf'])]),
        ),
        migrations.RunPython(date_existing_invoices, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='core_invoic_status_71224b_idx'),
        ),
    ]
