# Generated by Django 5.2.17 on 2026-08-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice_due_date_invoice_terms_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
