# Generated by Django 5.2.17 on 2026-08-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_stockmovement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('ISSUE', 'Issued by supplier'), ('RECEIPT', 'Received by hospital'), ('RETURN', 'Returned to supplier'), ('ADJUST', 'Manual adjustment'), ('DISPENSE', 'Dispensed by hospital')], max_length=10),
        ),
    ]
