# Generated by Django 5.2.17 on 2026-08-08 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_stockmovement_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryline',
            name='qty_accepted',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='qty_rejected',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='qty_supplied',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_order_qty',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cap per single request. Blank = no cap.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_reserved',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Approved but not yet dispatched. Held for those requests.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='qty_approved',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='qty_requested',
            field=models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='qty',
            field=models.DecimalField(decimal_places=1, help_text='Signed against the organization holding it.', max_digits=12),
        ),
    ]
