# Generated by Django 5.2.17 on 2026-08-08 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_deliveryline_qty_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='idle_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Ceiling on how long a signed-in app may sit idle before it signs itself out. A device may choose a shorter time, never a longer one.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(480)]),
        ),
    ]
