# Generated by Django 5.2.17 on 2026-08-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organization_idle_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
