# Generated by Django 5.2.17 on 2026-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UNIT', 'UNIT'), ('TABLET', 'TABLET'), ('CAPSULE', 'CAPSULE'), ('SACHET', 'SACHET'), ('BOTTLE', 'BOTTLE'), ('VIAL', 'VIAL'), ('AMPOULE', 'AMPOULE'), ('SYRINGE', 'SYRINGE'), ('SUPPOSITORY', 'SUPPOSITORY'), ('TUBE', 'TUBE'), ('STRIP', 'STRIP'), ('PACK', 'PACK'), ('CARTON', 'CARTON'), ('BOX', 'BOX'), ('KIT', 'KIT'), ('ROLL', 'ROLL'), ('PAIR', 'PAIR'), ('PIECE', 'PIECE'), ('ML', 'ML'), ('L', 'L'), ('MG', 'MG'), ('G', 'G'), ('KG', 'KG'), ('DROP', 'DROP')], default='UNIT', max_length=40),
        ),
    ]
