# Generated by Django 5.2.17 on 2026-08-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dispensingunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='dispensingunit',
            name='uniq_unit_per_supplier',
        ),
        migrations.RemoveConstraint(
            model_name='dispensingunit',
            name='uniq_shared_dispensing_unit',
        ),
        migrations.AlterField(
            model_name='dispensingunit',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='dispensingunit',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Blank for a standard term shared by every company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization'),
        ),
        migrations.AddConstraint(
            model_name='dispensingunit',
            constraint=models.UniqueConstraint(fields=('supplier', 'name'), name='uniq_dispensingunit_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='dispensingunit',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', True)), fields=('name',), name='uniq_shared_dispensingunit'),
        ),
        migrations.AddField(
            model_name='formulation',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Blank for a standard term shared by every company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization'),
        ),
        migrations.AddConstraint(
            model_name='formulation',
            constraint=models.UniqueConstraint(fields=('supplier', 'name'), name='uniq_formulation_per_supplier'),
        ),
        migrations.AddConstraint(
            model_name='formulation',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier__isnull', True)), fields=('name',), name='uniq_shared_formulation'),
        ),
    ]
