# Generated by Django 5.2.17 on 2026-08-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_formulation_row'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='core_auditl_organiz_e98001_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'product'], name='core_stockm_organiz_c321ce_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', '-created_at'], name='core_stockm_organiz_4c5c62_idx'),
        ),
    ]
