# Generated by Django 5.2.17 on 2026-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auditlog_core_auditl_organiz_e98001_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Warn when the available quantity falls below this. Blank falls back to the platform default, which is the same figure for everything and so is rarely the right one for anything.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'expiry_date'], name='core_stockm_organiz_05957a_idx'),
        ),
    ]
