# Generated by Django 5.2.17 on 2026-08-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_product_reorder_level_stockmovement_batch_no_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='uniq_payer_reference_per_invoice',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Recorded, awaiting the supplier'), ('CONFIRMED', 'Confirmed received'), ('REJECTED', 'Not received'), ('WITHDRAWN', 'Withdrawn by the hospital')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('payer_reference', ''), _negated=True), models.Q(('status__in', ['REJECTED', 'WITHDRAWN']), _negated=True)), fields=('invoice', 'payer_reference'), name='uniq_payer_reference_per_invoice'),
        ),
    ]
