# Generated by Django 5.2.17 on 2026-08-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_payment_uniq_payer_reference_per_invoice_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('supplier', 'generic_name', 'brand', 'strength'), name='uniq_product_per_supplier'),
        ),
    ]
