# Generated by Django 5.2.17 on 2026-08-13 19:50

import core.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_uniq_product_per_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=core.models.new_reference, max_length=16, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Raised, awaiting the supplier'), ('CONFIRMED', 'Accepted by the supplier'), ('REJECTED', 'Refused by the supplier')], default='PENDING', max_length=10)),
                ('reason', models.CharField(max_length=255)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_decided', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.invoice')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=1, max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.creditnote')),
                ('delivery_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_lines', to='core.deliveryline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['invoice', 'status'], name='core_credit_invoice_39699d_idx'),
        ),
    ]
