# Generated by Django 5.2.17 on 2026-08-14 17:01

import core.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_creditnote_creditnoteline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=core.models.new_reference, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested, awaiting the holding unit'), ('ISSUED', 'Issued'), ('REJECTED', 'Refused by the holding unit'), ('CANCELLED', 'Withdrawn by the asking unit')], default='REQUESTED', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, help_text='Why it was refused or withdrawn, or a remark on what was issued.', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=12)),
                ('qty_issued', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('ISSUE', 'Issued by supplier'), ('RECEIPT', 'Received by hospital'), ('RETURN', 'Returned to supplier'), ('ADJUST', 'Manual adjustment'), ('DISPENSE', 'Dispensed by hospital'), ('TRANSFER', 'Moved between units')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['unit', 'product'], name='core_stockm_unit_id_2a3a08_idx'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_unit',
            field=models.ForeignKey(blank=True, help_text='The unit being asked, which holds the stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='core.unit'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.organization'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_unit',
            field=models.ForeignKey(blank=True, help_text='The unit that asked, which the stock moves to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='core.unit'),
        ),
        migrations.AddField(
            model_name='transferline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='core.product'),
        ),
        migrations.AddField(
            model_name='transferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.transfer'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_unit', 'status'], name='core_transf_from_un_e4b9db_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_unit', 'status'], name='core_transf_to_unit_b2d3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['hospital', '-created_at'], name='core_transf_hospita_0df5b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transferline',
            unique_together={('transfer', 'product')},
        ),
    ]
