# Generated by Django 5.2.17 on 2026-08-14 17:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_transfer_transferline_stockmovement_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='issue_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='receipt_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferline',
            name='qty_approved',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='transferline',
            name='qty_received',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='transferline',
            name='shortfall_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='decision_note',
            field=models.CharField(blank=True, help_text='What the holding unit said when it agreed, refused, or was stood down.', max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested, awaiting the holding unit'), ('APPROVED', 'Agreed, awaiting the goods'), ('ISSUED', 'Handed over, awaiting confirmation'), ('RECEIVED', 'Confirmed received'), ('REJECTED', 'Refused by the holding unit'), ('CANCELLED', 'Withdrawn by the asking unit')], default='REQUESTED', max_length=10),
        ),
    ]
