# Generated by Django 5.2.17 on 2026-09-22 00:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_transfer_issue_note_transfer_issued_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('strength', models.CharField(blank=True, max_length=60)),
                ('qty', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dispensing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_items', to='core.dispensingunit')),
                ('formulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_items', to='core.formulation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.unit')),
            ],
            options={
                'ordering': ['name', 'strength'],
                'constraints': [models.UniqueConstraint(fields=('unit', 'name', 'brand', 'strength'), name='uniq_item_per_unit')],
            },
        ),
    ]
