# Generated by Django 5.2.17 on 2026-09-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_unititem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('UNIT_ADMIN', 'Unit administrator'), ('STAFF', 'Staff')], default='STAFF', max_length=12),
        ),
    ]
